#
# ~/.tmux.conf
#

# Enable mouse support
set -g mouse on

# Status line left side: session name
set -g status-left '[#{?#{e|>:#{server_sessions},1},:#S:,#S}] '
# Status line right side: cwd, git branch/status and running vm
set -g status-right "\
#{s|$HOME|~|:pane_current_path}\
  #(git -C '#{pane_current_path}' branch --show-current 2>/dev/null)\
#{?#(git -C '#{pane_current_path}' status --short),⚡, }\
#[reverse]#(\
sudo virsh list --name | sed '/^\s*$/d' |\
 tr '\n' ',' | sed 's/,/#[default]#[reverse]/g'\
)#[default]"

set -g status-left-length   40
set -g status-right-length  60
set -g status-style 'bg=terminal,bold,fg=#{?client_prefix,colour211,colour60}'
set -g status-keys vi

set -g display-panes-time   3000
set -g display-time         3000
set -g renumber-windows     on

# Borders
set -g display-panes-active-colour  yellow
set -g pane-border-style            black
set -g pane-active-border-style \
  '#{?pane_in_mode,fg=yellow,#{?synchronize-panes,fg=red,fg=blue}}'

# Set base index for windows and panes to 1
set -g base-index      1
set -g pane-base-index 1

# Split panes using | and -
bind-key | split-window -hc  '#{pane_current_path}'
bind-key - split-window -vc  '#{pane_current_path}'
bind-key _ split-window -vc  '#{pane_current_path}' -l 25%
bind-key e {
  resize-pane -t-1 -y 25%
  resize-pane -t+1 -y 25%
}
unbind '"'
unbind %

# join marked pane
bind-key j join-pane

# Activate/deactivate virtual environment using a
bind-key a send-keys Escape 'i' \
 '[[ -v VIRTUAL_ENV ]] && deactivate || source "$(find_venv.sh)/.venv/bin/activate"' C-m
# Source .tmux.conf
bind-key r source-file ~/.tmux.conf \; display-message "source-file done"

# Layouts
bind-key h select-layout even-horizontal
bind-key v select-layout even-vertical
bind-key B select-layout \
  '7a16,190x49,0,0{95x49,0,0,10,94x49,96,0[94x24,96,0,0,94x24,96,25,5]}'
bind-key b select-layout \
  '8f06,190x49,0,0{95x49,0,0[95x24,0,0,0,95x24,0,25,5],94x49,96,0,12}'

# Vi mode in copy mode
set -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection

# Enable history file
set -g history-file ~/.tmux_history
set -g history-limit 5000

# Change prefix key
set -g prefix M-/
unbind C-b
bind-key M-/ send-prefix

# Vim Tmux Navigator
# Smart pane switching with awareness of Vim splits.
# https://github.com/christoomey/vim-tmux-navigator
%hidden is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
bind-key -n 'C-\' if-shell "$is_vim" 'send-keys C-\\'  'select-pane -l'

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Open ptpython in a popup with chosen modules
bind-key 'C-p' display-popup -w 80 -h 24 -Ed '#{pane_current_path}' '
  tmux new-session -As "pt" "pt"'

# Open popup displaying tmux man page for specific command
bind-key 'C-d' {
  %hidden man_exists="tmux ls | grep '^man:'"
  if-shell "$man_exists" '' {
    display-popup -w 35 -h 14 -E \
      "man tmux | grep -Po '^\s{7}[a-z]+-[a-z]+(?=\s+\\[)' | fzf > /tmp/selected"
  }
  display-popup -w 80 -h 24 -E \
    "tmux new -As 'man' 'man tmux'\\; send \"/^\$(cat /tmp/selected) \" Enter"
}

# Open terminal in a popup
bind-key 'C-t' popup -w 80 -h 24 -Ed '#{pane_current_path}' 'tmux new -As "term"'
bind-key 'C-y' popup -w 80 -h 24 -Ed '#{pane_current_path}' 'tmux new -As "pty"'
